---
# Site Info
title: Concert for a Sustainable Planet
description:
url: http://carnegie2017.unsdsn.org
timezone: America/New_York
event_date: 7:30 pm, September 18, 2017
event_location: >
  Zankel Hall, Carnegie Hall, New York, USA
  Entrance on Seventh Avenue between 56th and 57th Streets
# Content Settings
collections:
  posts:
    title: Posts
    output: true
  performers:
    title: performers
    output: false
    url: false
  program:
    title: program
    output: false
    url: false
  sections:
    title: sections
    output: false
    url: false
markdown: kramdown
excerpt_separator: <!--more-->

# Contact Information
email: info@unsdsn.org
twitter_username: UNSDSN

# Jekyll Settings
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- Vagrantfile
- bootstrap.sh
- .vagrant
sass:
    sass_dir: _sass
    style: compressed

# Jekyll Livereload Settings
port: 4000
host: 0.0.0.0
livereload: true
