---
# Site Info
title: Concert for a Sustainable Planet
description: 'Music for sustainability'
url: http://carnegie2017.unsdsn.org
timezone: America/New_York

# Content Settings
collections:
  posts:
    title: Posts
    output: true
  artists:
    title: artists
    output: false
    url: false
markdown: kramdown
excerpt_separator: <!--more-->

# Contact Information
email: info@unsdsn.org
twitter_username: UNSDSN

# Jekyll Settings
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- Vagrantfile
- bootstrap.sh
- .vagrant

# Jekyll Livereload Settings
port: 4000
host: 0.0.0.0
livereload: true
