---
# Site Info
title: Concert for a Sustainable Planet
description:
url: http://cfsp18.unsdsn.org
timezone: America/New_York
event_date: September 26, 2018
event_location: Carnegie Hall, New York, USA

# Content Settings
collections:
  posts:
    title: Posts
    output: false
  performers:
    title: performers
    output: false
    url: false
  program:
    title: program
    output: false
    url: false
  sections:
    title: sections
    output: false
    url: false
markdown: kramdown
excerpt_separator: <!--more-->

# Contact Information
email: info@unsdsn.org
twitter_username: UNSDSN


# Jekyll Settings
theme: minima
exclude:
- Gemfile
- Gemfile.lock
- Vagrantfile
- bootstrap.sh
- .vagrant
sass:
    sass_dir: _sass
    style: compressed
